name: Make html
on:
  push:
    branches: [ main ]

jobs:
  changedfiles:
    runs-on: ubuntu-18.04
    outputs:
      md: ${{ steps.changes.outputs.md }}
      cv: ${{ steps.changes.outputs.cv }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Get changed files
        id: changes
        run: |
          MY_STRING=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep -o '^docs\/.*\.md' | while read -r line; do echo "$line"; done)
          MY_STRING="${MY_STRING//'%'/'%25'}"
          MY_STRING="${MY_STRING//$'\n'/'%0A'}"
          MY_STRING="${MY_STRING//$'\r'/'%0D'}"
          echo "::set-output name=md::$MY_STRING"
          echo "::set-output name=cv::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep -o '^cv\/.*' | xargs)"
  
  processing:
    runs-on: ubuntu-18.04
    needs: changedfiles
    if: ${{needs.changedfiles.outputs.md}}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Echo changed files
        run: echo "${{needs.changedfiles.outputs.md}}"
      - name: Process changed files
        run: |
          while read -r f; do
                echo "Working with file $f"
                echo "Generating ${f%.md}.html"
                cat $f | \
                docker run -i -v $(pwd):/data -w /data akiross/container-gpp -x -H -Iinclude | \
                cat - include/metadata.yaml | \
                docker run -i -v $(pwd):/data -w /data pandoc/core:2.9 -s -f \
                  markdown+link_attributes+smart+multiline_tables+escaped_line_breaks \
                  --data-dir=include \
                  --template=bootstrap-template.html \
                  --mathjax --toc -t html > ${f%.md}.html
          done <<< "${{needs.changedfiles.outputs.md}}"
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: .
          clean: false

  processingcv:
    runs-on: ubuntu-18.04
    needs: changedfiles
    if: ${{needs.changedfiles.outputs.cv}}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Process cv files
        run: |
          # build html file for bibliography in index.md
          cat cv/bibliography.bib | \
            docker run -i --entrypoint bib2bib tchumley/bibtex2html --no-comment -c 'author : "Chumley"' | \
            docker run -i tchumley/bibtex2html -nodoc -nokeys --no-keywords --style abbrv -q -r | \
            docker run -i pandoc/core -f html -t markdown | \
            sed -n '/------------------/q;p' | \
            awk ' /^$/ { print; } /./ { printf("%s ", $0); }' | \
            tac | \
            nl -bt -s '. ' -w 1 | \
            docker run -i pandoc/core -f markdown -t html | \
            sed 's/<ol/& reversed/' > include/bib-include.html
          # build md file for bibliography in cv.pdf
          cat cv/bibliography.bib | \
            docker run -i --entrypoint bib2bib tchumley/bibtex2html --no-comment -c 'author : "Chumley"' --remove doi --remove eprint --remove url | \
            docker run -i tchumley/bibtex2html -nodoc -nokeys --no-keywords --style abbrv -q -r | \
            docker run -i pandoc/core -f html -t markdown | \
            sed -n '/------------------/q;p' | \
            awk ' /^$/ { print; } /./ { printf("%s ", $0); }' | \
            tac | \
            nl -bt -s '. ' -w 1 > include/bib-include-no-links.md
          # build index.html
          cat docs/index.md | \
            docker run -i -v $(pwd):/data -w /data akiross/container-gpp -x -H -Iinclude | \
            cat - include/metadata.yaml | \
            docker run -i -v $(pwd):/data -w /data pandoc/core:2.9 -s -f \
              markdown+link_attributes+smart+multiline_tables+escaped_line_breaks \
              --data-dir=include \
              --template=bootstrap-template.html \
              --mathjax --toc -t html > docs/index.html
          # build cv.pdf
          cat cv/cv.md | \
            docker run -i -v $(pwd):/data -w /data akiross/container-gpp -x -H -Iinclude | \
            docker run -i -v $(pwd):/data -w /data pandoc/latex -f markdown -t latex | \
            cat cv/before.tex - cv/after.tex > cv/cv.tex
          cat cv/cv.tex
          docker run -i -v $(pwd):/data -w /data thomasweise/docker-texlive-thin latexmk -pdf cv/cv.tex
          mv cv/cv.pdf docs/cv.pdf
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: .
          clean: false
      - name: Deploy bib-include
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: main
          folder: include
          target-folder: include
          
